all: 
	gcc XOR_key.c -o dec -mno-cygwin -std=c99
	gcc virus.c -o virus -mno-cygwin -std=c99
	#gcc virus.c -o virus -mno-cygwin -std=c99
	#gcc find_dir.c -o find_dir -mno-cygwin -std=c99

	#gcc virus_pt.c -o payload  -mno-cygwin
	#gcc victim.c -o victim -mno-cygwin

clean:
	rm dec.exe
	rm virus.exe
	rm calc.exe
	